# Generated by Django 5.0.4 on 2024-05-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevaladded',
            name='status',
            field=models.CharField(choices=[('NW', 'Новый'), ('PN', 'Запрос рассматривается'), ('AC', 'Запрос успешно принят'), ('RJ', 'Запрос не принят')], default='NW', max_length=2),
        ),
    ]
